project:
  type: website

website:
  title: "PBDB explorer"
  description: "A website to explore the Paleobiology Database"
  sidebar: false
format:
  html:
    theme: cosmo
    css: styles.css
    


